name: CI (My App)

on:
  push:
    branches: [ main ]
    paths:
      - 'my_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'my_app/**'

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_app/.ruby-version
          bundler-cache: true
          working-directory: my_app

      - name: Scan for common Rails security vulnerabilities
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_app/.ruby-version
          bundler-cache: true
          working-directory: my_app

      - name: Scan JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_app/.ruby-version
          bundler-cache: true
          working-directory: my_app

      - name: Lint Ruby code
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_app/.ruby-version
          bundler-cache: true
          working-directory: my_app

      - name: Run Rails tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: my_app/tmp/screenshots
          if-no-files-found: ignore
